name: "AI Code Reviewer"
description: "Reviews PRs with OpenAI and assigns labels + reviewers"

inputs:
  OPENAI_API_KEY:
    description: "OpenAI API Key"
    required: true

runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run AI Review
      run: python main.py
      env:
        GITHUB_TOKEN: ${{ github.token }}
        OPENAI_API_KEY: ${{ inputs.OPENAI_API_KEY }}
