name: Deploy enclov-AI to Kubernetes

on:
  push:
    branches: [main]

permissions:
  contents: read
  packages: write
  deployments: write

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
           username: ${{ secrets.enclov-ai }}
          password: ${{ secrets.84298ed9f2470f159b48e36e76eb90eeac061941 }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: web4application.github.io/enclov-ai:latest

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Decode KUBECONFIG and set up
        run: |
          echo "${{ secrets.KUBECONFIG }}" | base64 --decode > $HOME/.kube/config

      - name: Deploy to Kubernetes
        run: kubectl apply -f k8s/
